export default {
  plants: {
    plant01: require('../assets/images/plants/plant01.png'),
    plant02: require('../assets/images/plants/plant02.png'),
    plant03: require('../assets/images/plants/plant03.png'),
    plant04: require('../assets/images/plants/plant04.png'),
    plant101: require('../assets/images/plants/plant101.png'),
    plant102: require('../assets/images/plants/plant102.png'),
    plant103: require('../assets/images/plants/plant103.png'),
    plant104: require('../assets/images/plants/plant104.png'),
    plant105: require('../assets/images/plants/plant105.png'),
    plant106: require('../assets/images/plants/plant106.png'),
    plant107: require('../assets/images/plants/plant107.png'),
    plant108: require('../assets/images/plants/plant108.png'),
    plant109: require('../assets/images/plants/plant109.png'),
    plant110: require('../assets/images/plants/plant110.png'),
    plant111: require('../assets/images/plants/plant111.png'),
  },
  rooms: {
    balcony: require('../assets/images/rooms/balcony.jpg'),
    bedroom01: require('../assets/images/rooms/bedroom-1.jpg'),
    bedroom02: require('../assets/images/rooms/bedroom-2.jpg'),
    bedroom03: require('../assets/images/rooms/bedroom-3.jpg'),
    diningRoom: require('../assets/images/rooms/dining-room.jpg'),
    foyer: require('../assets/images/rooms/foyer.jpg'),
    garage: require('../assets/images/rooms/garage.jpg'),
    hallway: require('../assets/images/rooms/hallway.jpg'),
    kitchen: require('../assets/images/rooms/kitchen.jpg'),
    livingRoom: require('../assets/images/rooms/living-room.jpg'),
    office: require('../assets/images/rooms/office.jpg'),
    patio: require('../assets/images/rooms/patio.jpg'),
    terrace: require('../assets/images/rooms/terrace.jpg'),
  },
};
